version: '3.8'

services:
  app:
    # Build from source for local development
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MAX_CONTENT_LENGTH=200
      - UPLOAD_TIMEOUT=300
    volumes:
      - ./uploads:/app/uploads
      - ./extracted:/app/extracted
      - ./logs:/app/logs
      # Mount source code for live reloading during development
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rpger-network:
    driver: bridge

volumes:
  uploads:
  extracted:
  logs:
